#!/usr/bin/env bash

set -eo pipefail

if [ -f .env ]; then
  # shellcheck disable=SC2002,SC2046
  export $(cat .env | xargs)
fi

function setup {
  poetry install
  poetry run pre-commit install
}

function test {
  local target="${1-"dbt-duckdb"}"

  if [ -z "${GITHUB_ACTIONS}" ] && [ "${target}" = "dbt-postgres" ];
  then
    createdb "${POSTGRES_DB-"dbt_linreg"}" || true
  fi

  if [ -z "${GITHUB_ACTIONS}" ] && [ "${target}" = "dbt-duckdb" ];
  then
    rm -f dbt.duckdb
  fi

  poetry run python scripts.py gen-test-cases --skip-if-exists
  poetry run dbt deps \
    --project-dir ./integration_tests \
    --profiles-dir ./integration_tests/profiles \
    --target "${target}"
  poetry run dbt seed \
    --project-dir ./integration_tests \
    --profiles-dir ./integration_tests/profiles \
    --target "${target}"
  poetry run dbt run \
    --project-dir ./integration_tests \
    --profiles-dir ./integration_tests/profiles \
    --target "${target}" \
    --selector "${target}-selector"
  poetry run dbt test \
    --project-dir ./integration_tests \
    --profiles-dir ./integration_tests/profiles \
    --target "${target}" \
    --selector "${target}-selector"
}

function lint {
  poetry run pre-commit run -a
}

function docs:deploy {
  mkdocs gh-deploy -f docs/mkdocs.yml
}

function help {
  echo "$0 <task> <args>"
  echo "Tasks:"
  compgen -A function | cat -n
}

TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
