#!/usr/bin/env bash

set -eo pipefail

function setup {
	poetry install
	poetry run pre-commit install
}

function testloc {
  # rm -f integration_tests/dbt.duckdb
  export DBT_PROFILES_DIR=./integration_tests/profiles
  poetry run dbt deps --project-dir ./integration_tests
  # poetry run dbt compile --project-dir ./integration_tests --select tag:perftest
  poetry run dbt run --project-dir ./integration_tests --select tag:perftest
}

function test {
  # rm -f integration_tests/dbt.duckdb
  export DBT_PROFILES_DIR=./integration_tests/profiles
  poetry run python scripts.py gen-test-cases
  poetry run dbt deps --project-dir ./integration_tests
  poetry run dbt seed --project-dir ./integration_tests
  poetry run dbt run --project-dir ./integration_tests
  poetry run dbt test --project-dir ./integration_tests
}

function lint {
  poetry run pre-commit run -a
}

function docs:deploy {
  mkdocs gh-deploy -f docs/mkdocs.yml
}

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
