name: "dbt_linreg_tests"
version: "0.1.1"

require-dbt-version: [">=1.0.0", "<2.0.0"]

config-version: 2

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
macro-paths: ["macros"]
log-path: "logs"

# During dev only!
profile: "dbt_linreg_profile"
