dbt_linreg_profile:
  target: duckdb
  outputs:
    duckdb:
      type: duckdb
      path: dbt.duckdb
    postgres:
      type: postgres
      user: '{{ env_var("POSTGRES_USER") }}'
      password: '{{ env_var("POSTGRES_PASSWORD") }}'
      host: '{{ env_var("POSTGRES_HOST", "localhost") }}'
      port: '{{ env_var("POSTGRES_PORT", "5432") | as_number }}'
      dbname: '{{ env_var("POSTGRES_DB", "dbt_linreg") }}'
      schema: '{{ env_var("POSTGRES_SCHEMA", "public") }}'
    clickhouse:
      type: clickhouse
      port: 8123
      user: dbt_user
      password: dbt_user_password
      schema: dbt_linreg
