name: docs
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt-get update
    - name: Deploy docs
      uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CONFIG_FILE: docs/mkdocs.yml
        REQUIREMENTS: docs/requirements.txt
